# build cmd: docker build -f ./Dockerfile.postgres -t antik-moderne-postgresdb:latest .
# run cmd: docker run -d -p 5432:5432 --name antik-moderne-postgresdb antik-moderne-postgresdb:latest 

# Used postgres:latest which introduced larger image size - could be reduced by using alpine
# Current image size: 459MB
# FROM postgres:latest

# Current image size: 270
FROM postgres:17.5-alpine

# # Set environment variables (optional, can also be set in docker-compose)
# ENV POSTGRES_PASSWORD=admin

# # Copy migration files
# COPY ./backend/users/src/db/migrations/ /docker-entrypoint-initdb.d/migrations_users
# COPY ./backend/products/src/db/migrations/ /docker-entrypoint-initdb.d/migrations_products
# COPY ./backend/baskets/src/db/migrations/ /docker-entrypoint-initdb.d/migrations_baskets

# # Copy the initialization script into the container
# COPY ./init-migrations.sh /docker-entrypoint-initdb.d/
# RUN chmod +x /docker-entrypoint-initdb.d/init-migrations.sh

# Expose the PostgreSQL port
EXPOSE 5432

# Define a volume for persistent data
VOLUME ["/var/lib/postgresql/data"]