apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gatekeeper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-gatekeeper-service
  template:
    metadata:
      labels:
        app: auth-gatekeeper-service
    spec:
      containers:
        - name: auth-gatekeeper-service
          image: antik-moderne-auth-gatekeeper-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: auth-gatekeeper-config
                  key: NODE_ENV
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: auth-gatekeeper-config
                  key: CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: auth-gatekeeper-config
                  key: CLERK_SECRET_KEY
            - name: WEBHOOK_SECRET_SIGNING_KEY
              valueFrom:
                configMapKeyRef:
                  name: auth-gatekeeper-config
                  key: WEBHOOK_SECRET_SIGNING_KEY