apiVersion: v1
kind: Service
metadata:
  name: auth-gatekeeper-service
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    app: auth-gatekeeper-service