apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgresdb
  ports:
    - name: postgresdb
      port: 5432
      targetPort: 5432
      nodePort: 30032
  type: NodePort