apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        # image: antik-moderne-products-service:latest
        image: ghcr.io/realkoder/antik-moderne-diy-products-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3004
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3005
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3005
        #   initialDelaySeconds: 5
        #   periodSeconds: 5