FROM node:23-alpine AS develop

WORKDIR /app

COPY package*.json ./

RUN npm install --global nodemon

RUN npm install

COPY . .

CMD npx prisma migrate deploy --schema=./src/db/schema.prisma && npm run dev