name: Build and Push Docker Images auth-gatekeeper

on:
  push:
    branches: [main]
    # paths:
    #   - 'backend/auth-gatekeeper/**'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_AUTH_GATEKEEPER: realkoder/antik-moderne-diy-auth-gatekeeper

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push auth-gatekeeper docker image
      - name: Build and push auth-gatekeeper Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AUTH_GATEKEEPER }}:latest ./backend/auth-gatekeeper
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AUTH_GATEKEEPER }}:latest